name: GR Viajes Bot

on:
  workflow_dispatch:

jobs:
  prueba:

    runs-on: ubuntu-latest

    steps:

      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar programa
        env:
          TOKEN_TELEGRAM: ${{ secrets.TOKEN_TELEGRAM }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          API_KEY: ${{ secrets.API_KEY }}
        run: python main.py
